version: '3.8'

services:

    mysql_8.2.X:
        # jdbc:mysql://localhost:33082/guest?user=guest&password=guest
        container_name: mysql_8.2.X
        image: mysql:8.2
        ports:
            - "33082:3306"
        env_file: mysql.env
        command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci, --log-bin-trust-function-creators=true, --default_authentication_plugin=mysql_native_password]
        healthcheck:
            test: "exit 0"

    maria_11.X:
        # jdbc:mariadb://localhost:33107/guest?user=guest&password=guest
        container_name: maria_11.X
        image: mariadb:11
        ports:
            - "33107:3306"
        env_file: mysql.env
        command: [mariadbd, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
        healthcheck:
            test: "exit 0"

    manticore:
        container_name: manticore
        image: manticoresearch/manticore
        restart: always
        ports:
            - 9306:9306
            - 9308:9308    
        environment:
        - MCL=1


