version: '3.8'

services:

    db2_11.5:
      # jdbc:db2://localhost:50002/testdb:user=db2inst1;password=My@Super@Secret;
      container_name: db2_11.5
      privileged: true
      image: datagrip/db2:11.5.8
      ports:
        - "50002:50000"
      env_file: ./db2.env
      healthcheck:
        test: find /database/config/.shared-data/ -name setup_complete || exit 1
        interval: 3m
        timeout: 10s
        retries: 5

    mongo_7:
      container_name: mongo_7
      image: datagrip/mongodb:7
      ports:
        - "27024:27017"
      env_file: .env
      healthcheck:
        test: "exit 0"

    redis_7:
      container_name: redis_7
      image: redis:7-alpine
      ports:
        - "6381:6379"
      healthcheck:
        test: "exit 0"
        interval: 2m
        timeout: 10s
        retries: 5